DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 4
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 4

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]
  RRCROP_SCALE: (0.5, 1.0)

OPTIM:
  NAME: "sgd"
  LR: 0.000015
  MAX_EPOCH: 2
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 0
  WARMUP_TYPE: "linear"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  MAILSRC_Trainer:
    RANK: 4
    IVLU_START_LAYER: 1
    IVLU_END_LAYER: 12 # end layer of ivlu
    START_LAYER: 1
    END_LAYER: 12
    PREC: "amp"
    TEXT_LOSS_WEIGHT: 0.0
    IMAGE_LOSS_WEIGHT: 0.0 # this has a great impact to overfit (benefit)
    LOGIT_LOSS_WEIGHT: 0.0 # this should be fixed as 1 forever :）

